# Optional: App Engine configuration (if using App Engine instead of Cloud Run)
runtime: python311

entrypoint: uvicorn main:app --host 0.0.0.0 --port 8080

instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 10

env_variables:
  PYTHONUNBUFFERED: "1"
